name: Gradle CI
on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  publish-docs:
    runs-on: ubuntu-latest
    name: Publish Docs
    needs: build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: Deploy Docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: build/dokka/html
